### ISSUE TITLE
CRM-21140

### ISSUE THREAD

**Issue by MegaphoneJon** [JMAConsulting/biz.jmaconsulting.contributionpagecustomfield#2]
Now that https://github.com/civicrm/civicrm-core/pull/11567 has been merged, you can probablyremove some of the code from this extension, since the API handles custom fields on all entities correctly now.

**Comment by monishdeb** [comment]
Thanks @MegaphoneJon for notifying the improvement. I have submitted a PR https://github.com/JMAConsulting/biz.jmaconsulting.contributionpagecustomfield/pull/3 , can you please check the PR and let me know if its ok to merge ? Thanks

**Comment by MegaphoneJon** [comment]
Hi @monishdeb - I've never used this extension, I don't even remember why I came across this!  Sorry for not being able to make space for review.

**Comment by JoeMurray** [comment]
@seamuslee001 please review and commit if appropriate.

**Comment by nickchu852** [comment]
I downloaded and unzipped the file, but CiviCRM does not show this plugin as available for installation.
