### ISSUE TITLE
Adding 'File' fields

### ISSUE THREAD

**Issue by KatyMoon** [JMAConsulting/biz.jmaconsulting.contributionpagecustomfield#5]
Excited to find this extension. Currently able to successfully add other field types, but when I add a 'File' field, it shows up on the form, but doesn't save the value when I save the form. Any thoughts?

**Comment by JoeMurray** [comment]
Heh @KatyMoon !

We seem to have not implemented custom fields of file type by the look of the code, since they require a bit more work. 

Our practice is generally to charge for enhancements. This one is small, but we're really over-busy at the moment.

**Comment by KatyMoon** [comment]
@JoeMurray Thanks for the quick response. That makes sense. I'll have to stick with a hodgepodge of CiviCRM Entity and native CiviContribution screens for now. I can pass this on to the client if you want to let me know the cost and when you might have time for this?

**Comment by JoeMurray** [comment]
Thanks for the offer. Let's say USD$250, and it would take 2 weeks.

**Comment by emptyhometax** [comment]
I have the custom field showing up on when I configure the contribution page but on the web form  it is not showing on the web form. Any thoughts?  
![image](https://user-images.githubusercontent.com/84540622/119036926-33b16a80-b966-11eb-9713-eac101268d37.png)

**Comment by JoeMurray** [comment]
Closing original issues. 

@emptyhometax I think you are mistaken about the purpose of this extension. 

A question 'Are you currently employed?' is really best included most likely as a custom field on the contact, and exposed on the contribution form as a profile. This repo is for fields that are about the contribution page, not about people submitting contributions through the page.
